### ISSUE TITLE
Style with CSS

### ISSUE THREAD

**Issue by cyouh95** [splishsplosh26/prj-rev-bwfs-dasmoto#3]
I would recommend all the styling of elements go in your CSS file instead of using the `style` attribute or `strong` tags. For example:

HTML
```html
<span class="price">Starting at $3.00 / brush.</span>
```

CSS
```css
.price {
  font-weight: bold;
  color: blue;
}
```

https://github.com/splishsplosh26/prj-rev-bwfs-dasmoto/blob/master/Project%201%20-%20Dasmotos/index.html#L15
